name: Notify Main Repository
on:
  push:
    branches:
      - main
      - master
jobs:
  extract-frontmatter:
    uses: ./.github/workflows/extract_frontmatter.yaml
    with:
      commit_count: 1

  notify:
    runs-on: ubuntu-24.04
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: tkgstrator/erudite-blog
          event-type: content-updated

  post:
    needs: extract-frontmatter
    uses: ./.github/workflows/post_bluesky.yaml
    with:
      frontmatters: ${{ needs.extract-frontmatter.outputs.frontmatters }}
    secrets:
      BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}